echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "We are learning Branching"
echo "I am learning Git"
echo "Editing script1"
echo "Editing today on 15th May 2026"
echo "Editing script1 on 16th May 2026"
echo "Editing script1 on 17th May 2026"